
# generated rest file from node-trekker
#model name - post

# GET all of the instances of a certain model
GET http://localhost:3001/posts
# Content-type: application/json


###




# GET a single instance of a certain model by id
GET http://localhost:3001/posts/61779320c6bda1e20ef7ed1d
Content-type: application/json


###



# POST a single new instance of a certain model
POST http://localhost:3001/posts
Content-type: application/json 

{
 	"title": "Test value 2" 
}



###



# PATCH a single instance of a certain model
PATCH http://localhost:3001/posts/61779397c6bda1e20ef7ed23
Content-type: application/json 

{
 	"title": "Test value 3" 
}



###



# DELETE a single instance of a certain model
DELETE http://localhost:3001/posts/61779397c6bda1e20ef7ed23
Content-type: application/json

