
# generated rest file from node-trekker
#model name - post

# GET all of the instances of a certain model
GET http://localhost:3001/posts/images/imagebyid/0.2706051472819926
# Content-type: application/json


###




# GET a single instance of a certain model by id
GET http://localhost:3001/posts/newIdGoesHere
Content-type: application/json


###



# POST a single new instance of a certain model
POST http://localhost:3001/posts
Content-type: application/json 

{
  
 	"title": "Test value" 
}



###



# PATCH a single instance of a certain model
PATCH http://localhost:3001/posts/newIdGoesHere
Content-type: application/json 

{
  
 	"title": "Test value" 
}



###



# DELETE a single instance of a certain model
DELETE http://localhost:3001/posts/newIdGoesHere
Content-type: application/json

